### PR TITLE
Added Hex Colour support

### PR DESCRIPTION
**Pull request by CoolDCB**
I've added Hex Colour support by using ChatColorHandler in the format of either '&#rrggbb' or by using MiniMessage (All legacy colours will still work)

_You can remove the discord.xml file, that is something from my IDE, wasn't originally aware that the .idea folder was included haha_

### CODE REVIEW

**Comment by CoolDCB** [comment]
I've updated the SDK version to Java 17. It allows ChatColorHandler to work and 1.8 is now an out of date Java version to be using for Minecraft eitherway!

**Review by zachduda — COMMENTED** [review]
Thanks for the pull! Looks good so far. I'll compile a test once I get back home and merge.

**Comment by CoolDCB** [comment]
Sounds good :)

**Comment by zachduda** [comment]
Works beautifully however the .jar size has increased by 548% after shading in the repository used for hex support. It seems a large portion of Kyori's Minimsg adventure repo is being included in this. I'll keep it merged for now as its more of a nit-pick, but personally I think there's a slightly more economical approach

**Comment by CoolDCB** [comment]
Yeahh, you're right I just changed this in the newest version of ChatColorHandler so that it is provided in the maven of  whichever plugin is using it. I'll have a look on the morning (GMT) to see if I'm doing anything stupid.

**Pull request merged**
